### ISSUE TITLE
INSTALL file out of date and has bad link

### ISSUE THREAD

**Issue by mathomp4** [ecmwf/ecbuild#10]
I'm a new user to `ecbuild` trying to build, install, and use it for the first time. So, since there wasn't a `README.md` file, I turned to `INSTALL`. However a link in that:
https://github.com/ecmwf/ecbuild/blob/f8a92b8102e85b560b0382aeaa9fc293170eca25/INSTALL#L7
no longer exists on ECMWF's wiki/Confluence. (The same goes for the link that is in the project's description: https://software.ecmwf.int/wiki/display/ecbuild which redirects to: https://confluence.ecmwf.int//display/ecbuild which I get a "Not Permitted" error when viewing.)

Also: 
https://github.com/ecmwf/ecbuild/blob/f8a92b8102e85b560b0382aeaa9fc293170eca25/INSTALL#L15
refers to an old version and I believe the releases aren't even named like that if you use the GitHub auto-generated releases here.

I'm assuming, though, that the installation method via CMake is still correct?

**Comment by jarethholt** [comment]
I am also a new user to ecbuild and was able to get it installed today. I found that the CMake installation method was still correct, though I also passed in `-DCMAKE_INSTALL_PREFIX=/my/install/path` since I wasn't installing globally. My build script looks like

    builddir=/myhome/ecbuild/build
    mkdir -p $builddir
    cd $builddir
    cmake \
      -DCMAKE_MODULE_PATH=$builddir \
      -DCMAKE_INSTALL_PREFIX=$builddir \
      .. |& tee cmake.log
    make install |& tee make.log

Also, for some reason `git clone https://github.com/ecmwf/ecbuild.git` grabs the `develop` branch by default. That wasn't working for me when compiling something else, so I used `git clone https://github.com/ecmwf/ecbuild.git --branch master`.

**Comment by tlmquintino** [comment]
We have now changed the default branch to master. 
Thanks for reporting.

**Comment by tlmquintino** [comment]
Regarding the README, thanks for the feedback. We will add a README.md for the upcoming release of ecbuild 3.0.0 (currently in develop branch).

**Comment by tlmquintino** [comment]
We also plan to move the documentation to somewhere more accessible (such as GitHub hosting)

**Comment by mathomp4** [comment]
@tlmquintino I suppose this can be closed now? I noticed that on the releases page, it looks like ecbuild 3+ has been tagged (if not "formally Github released")
